### ISSUE TITLE
Unhandled exception. System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by ydsumith** [ydsumith/Achilles-Contact-Angle#1]
Dear Dr. Yesudasan,

I really appreciate your time and consideration. Thank you for your new version of the software.

I have problems in running the software, even with your samples that have one atom type for both droplet and surface. And this is the error:

C:\Sumith_Projects\testing\net5.0>Achilles.exe
Estimating Contact angle.
Check debug_images/a_logfile.txt...
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Achilles.Program.Read_settings() in C:\Sumith_Projects\C#_projects\Contact angle\Achillies\Achillies\Program.cs:line 71
   at Achilles.Program.Main() in C:\Sumith_Projects\C#_projects\Contact angle\Achillies\Achillies\Program.cs:line 60

How can I solve this problem?

Best wishes,

Neda xxxxxx (name redacted)

**Comment by ydsumith** [comment]
This usually happens when the input data file is corrupted.
I have fixed the code to handle this exception.
